name: Scrape Extension Data

on:
  schedule:
    - cron: "0 0 * * *"   # Run once at midnight UTC
    - cron: "0 12 * * *"  # Run once at noon UTC
  workflow_dispatch:      # Allows manual triggering
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scraper/requirements.txt

    - name: Run the scraper script
      run: python scraper/scrape.py

    - name: Commit and push results
      uses: EndBug/add-and-commit@v9
      with:
        author_name: "github-actions[bot]"
        author_email: "github-actions[bot]@users.noreply.github.com"
        message: "Scrape extension data and update results"
        add: "docs/extension_data.json"
